version: '3.9'

services:
  web:
    build: .
    image: chatgpt:v1
    container_name: chatgpt
    working_dir: '/var/www/html'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 8088:80
    env_file:
      - .env

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"